-- AURA AI Supabase schema migration
-- Run this in Supabase Dashboard -> SQL Editor

-- Users table
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  email text unique not null,
  name text not null,
  password text not null,
  target_role text not null default '',
  target_industry text not null default '',
  experience_level text not null default 'Mid',
  resume_score integer not null default 0,
  email_verified boolean not null default false,
  verification_code text not null default '',
  role text not null default 'user'
);

-- Applications table
create table if not exists public.applications (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  email text not null references public.users(email) on delete cascade,
  data jsonb not null default '[]'::jsonb
);

-- Resumes table
create table if not exists public.resumes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  email text not null references public.users(email) on delete cascade,
  data jsonb not null default '{}'::jsonb
);

-- Roadmaps table
create table if not exists public.roadmaps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  email text not null references public.users(email) on delete cascade,
  data jsonb not null default '[]'::jsonb
);

-- Chats table
create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  email text not null references public.users(email) on delete cascade,
  data jsonb not null default '{}'::jsonb
);

-- Indexes
create index if not exists idx_users_email on public.users(email);
create index if not exists idx_applications_email on public.applications(email);
create index if not exists idx_resumes_email on public.resumes(email);
create index if not exists idx_roadmaps_email on public.roadmaps(email);
create index if not exists idx_chats_email on public.chats(email);
